<?php
namespace OpenBoleto;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:16:52.
 */
class AgenteTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Agente
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Agente;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers OpenBoleto\Agente::setCep
     * @todo   Implement testSetCep().
     */
    public function testSetCep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::getCep
     * @todo   Implement testGetCep().
     */
    public function testGetCep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::setCidade
     * @todo   Implement testSetCidade().
     */
    public function testSetCidade()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::getCidade
     * @todo   Implement testGetCidade().
     */
    public function testGetCidade()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::setDocumento
     * @todo   Implement testSetDocumento().
     */
    public function testSetDocumento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::getDocumento
     * @todo   Implement testGetDocumento().
     */
    public function testGetDocumento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::setEndereco
     * @todo   Implement testSetEndereco().
     */
    public function testSetEndereco()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::getEndereco
     * @todo   Implement testGetEndereco().
     */
    public function testGetEndereco()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::setNome
     * @todo   Implement testSetNome().
     */
    public function testSetNome()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::getNome
     * @todo   Implement testGetNome().
     */
    public function testGetNome()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::setUf
     * @todo   Implement testSetUf().
     */
    public function testSetUf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::getUf
     * @todo   Implement testGetUf().
     */
    public function testGetUf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::getNomeDocumento
     * @todo   Implement testGetNomeDocumento().
     */
    public function testGetNomeDocumento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::getTipoDocumento
     * @todo   Implement testGetTipoDocumento().
     */
    public function testGetTipoDocumento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\Agente::getCepCidadeUf
     * @todo   Implement testGetCepCidadeUf().
     */
    public function testGetCepCidadeUf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
