<?php
namespace OpenBoleto;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:16:53.
 */
class BoletoAbstractTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BoletoAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BoletoAbstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setAgencia
     * @todo   Implement testSetAgencia().
     */
    public function testSetAgencia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getAgencia
     * @todo   Implement testGetAgencia().
     */
    public function testGetAgencia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setAgenciaDv
     * @todo   Implement testSetAgenciaDv().
     */
    public function testSetAgenciaDv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getAgenciaDv
     * @todo   Implement testGetAgenciaDv().
     */
    public function testGetAgenciaDv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setCarteira
     * @todo   Implement testSetCarteira().
     */
    public function testSetCarteira()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getCarteira
     * @todo   Implement testGetCarteira().
     */
    public function testGetCarteira()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getCarteiras
     * @todo   Implement testGetCarteiras().
     */
    public function testGetCarteiras()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setCedente
     * @todo   Implement testSetCedente().
     */
    public function testSetCedente()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getCedente
     * @todo   Implement testGetCedente().
     */
    public function testGetCedente()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getCodigoBanco
     * @todo   Implement testGetCodigoBanco().
     */
    public function testGetCodigoBanco()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setConta
     * @todo   Implement testSetConta().
     */
    public function testSetConta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getConta
     * @todo   Implement testGetConta().
     */
    public function testGetConta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setContaDv
     * @todo   Implement testSetContaDv().
     */
    public function testSetContaDv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getContaDv
     * @todo   Implement testGetContaDv().
     */
    public function testGetContaDv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setDataVencimento
     * @todo   Implement testSetDataVencimento().
     */
    public function testSetDataVencimento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getDataVencimento
     * @todo   Implement testGetDataVencimento().
     */
    public function testGetDataVencimento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setContraApresentacao
     * @todo   Implement testSetContraApresentacao().
     */
    public function testSetContraApresentacao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getContraApresentacao
     * @todo   Implement testGetContraApresentacao().
     */
    public function testGetContraApresentacao()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setDataDocumento
     * @todo   Implement testSetDataDocumento().
     */
    public function testSetDataDocumento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getDataDocumento
     * @todo   Implement testGetDataDocumento().
     */
    public function testGetDataDocumento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setAceite
     * @todo   Implement testSetAceite().
     */
    public function testSetAceite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getAceite
     * @todo   Implement testGetAceite().
     */
    public function testGetAceite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setEspecieDoc
     * @todo   Implement testSetEspecieDoc().
     */
    public function testSetEspecieDoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getEspecieDoc
     * @todo   Implement testGetEspecieDoc().
     */
    public function testGetEspecieDoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setNumeroDocumento
     * @todo   Implement testSetNumeroDocumento().
     */
    public function testSetNumeroDocumento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getNumeroDocumento
     * @todo   Implement testGetNumeroDocumento().
     */
    public function testGetNumeroDocumento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setSequencial
     * @todo   Implement testSetSequencial().
     */
    public function testSetSequencial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getSequencial
     * @todo   Implement testGetSequencial().
     */
    public function testGetSequencial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setUsoBanco
     * @todo   Implement testSetUsoBanco().
     */
    public function testSetUsoBanco()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getUsoBanco
     * @todo   Implement testGetUsoBanco().
     */
    public function testGetUsoBanco()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setDataProcessamento
     * @todo   Implement testSetDataProcessamento().
     */
    public function testSetDataProcessamento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getDataProcessamento
     * @todo   Implement testGetDataProcessamento().
     */
    public function testGetDataProcessamento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setInstrucoes
     * @todo   Implement testSetInstrucoes().
     */
    public function testSetInstrucoes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getInstrucoes
     * @todo   Implement testGetInstrucoes().
     */
    public function testGetInstrucoes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setDescricaoDemonstrativo
     * @todo   Implement testSetDescricaoDemonstrativo().
     */
    public function testSetDescricaoDemonstrativo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getDescricaoDemonstrativo
     * @todo   Implement testGetDescricaoDemonstrativo().
     */
    public function testGetDescricaoDemonstrativo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setLocalPagamento
     * @todo   Implement testSetLocalPagamento().
     */
    public function testSetLocalPagamento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getLocalPagamento
     * @todo   Implement testGetLocalPagamento().
     */
    public function testGetLocalPagamento()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setMoeda
     * @todo   Implement testSetMoeda().
     */
    public function testSetMoeda()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getMoeda
     * @todo   Implement testGetMoeda().
     */
    public function testGetMoeda()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setSacado
     * @todo   Implement testSetSacado().
     */
    public function testSetSacado()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getSacado
     * @todo   Implement testGetSacado().
     */
    public function testGetSacado()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setSacadorAvalista
     * @todo   Implement testSetSacadorAvalista().
     */
    public function testSetSacadorAvalista()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getSacadorAvalista
     * @todo   Implement testGetSacadorAvalista().
     */
    public function testGetSacadorAvalista()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setValor
     * @todo   Implement testSetValor().
     */
    public function testSetValor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getValor
     * @todo   Implement testGetValor().
     */
    public function testGetValor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setDescontosAbatimentos
     * @todo   Implement testSetDescontosAbatimentos().
     */
    public function testSetDescontosAbatimentos()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getDescontosAbatimentos
     * @todo   Implement testGetDescontosAbatimentos().
     */
    public function testGetDescontosAbatimentos()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setMoraMulta
     * @todo   Implement testSetMoraMulta().
     */
    public function testSetMoraMulta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getMoraMulta
     * @todo   Implement testGetMoraMulta().
     */
    public function testGetMoraMulta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setOutrasDeducoes
     * @todo   Implement testSetOutrasDeducoes().
     */
    public function testSetOutrasDeducoes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getOutrasDeducoes
     * @todo   Implement testGetOutrasDeducoes().
     */
    public function testGetOutrasDeducoes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setOutrosAcrescimos
     * @todo   Implement testSetOutrosAcrescimos().
     */
    public function testSetOutrosAcrescimos()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getOutrosAcrescimos
     * @todo   Implement testGetOutrosAcrescimos().
     */
    public function testGetOutrosAcrescimos()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setQuantidade
     * @todo   Implement testSetQuantidade().
     */
    public function testSetQuantidade()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getQuantidade
     * @todo   Implement testGetQuantidade().
     */
    public function testGetQuantidade()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setValorCobrado
     * @todo   Implement testSetValorCobrado().
     */
    public function testSetValorCobrado()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getValorCobrado
     * @todo   Implement testGetValorCobrado().
     */
    public function testGetValorCobrado()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setValorUnitario
     * @todo   Implement testSetValorUnitario().
     */
    public function testSetValorUnitario()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getValorUnitario
     * @todo   Implement testGetValorUnitario().
     */
    public function testGetValorUnitario()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setPagamentoMinimo
     * @todo   Implement testSetPagamentoMinimo().
     */
    public function testSetPagamentoMinimo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getPagamentoMinimo
     * @todo   Implement testGetPagamentoMinimo().
     */
    public function testGetPagamentoMinimo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setLayout
     * @todo   Implement testSetLayout().
     */
    public function testSetLayout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getLayout
     * @todo   Implement testGetLayout().
     */
    public function testGetLayout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setResourcePath
     * @todo   Implement testSetResourcePath().
     */
    public function testSetResourcePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getResourcePath
     * @todo   Implement testGetResourcePath().
     */
    public function testGetResourcePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setLogoBanco
     * @todo   Implement testSetLogoBanco().
     */
    public function testSetLogoBanco()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getLogoBanco
     * @todo   Implement testGetLogoBanco().
     */
    public function testGetLogoBanco()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getLogoBancoBase64
     * @todo   Implement testGetLogoBancoBase64().
     */
    public function testGetLogoBancoBase64()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setLogoPath
     * @todo   Implement testSetLogoPath().
     */
    public function testSetLogoPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getLogoPath
     * @todo   Implement testGetLogoPath().
     */
    public function testGetLogoPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::setNossoNumero
     * @todo   Implement testSetNossoNumero().
     */
    public function testSetNossoNumero()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getNossoNumero
     * @todo   Implement testGetNossoNumero().
     */
    public function testGetNossoNumero()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getViewVars
     * @todo   Implement testGetViewVars().
     */
    public function testGetViewVars()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getOutput
     * @todo   Implement testGetOutput().
     */
    public function testGetOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getAgenciaCodigoCedente
     * @todo   Implement testGetAgenciaCodigoCedente().
     */
    public function testGetAgenciaCodigoCedente()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getCarteiraNome
     * @todo   Implement testGetCarteiraNome().
     */
    public function testGetCarteiraNome()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getNumeroFebraban
     * @todo   Implement testGetNumeroFebraban().
     */
    public function testGetNumeroFebraban()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getCodigoBancoComDv
     * @todo   Implement testGetCodigoBancoComDv().
     */
    public function testGetCodigoBancoComDv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getLinhaDigitavel
     * @todo   Implement testGetLinhaDigitavel().
     */
    public function testGetLinhaDigitavel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoAbstract::getImagemCodigoDeBarras
     * @todo   Implement testGetImagemCodigoDeBarras().
     */
    public function testGetImagemCodigoDeBarras()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
