<?php
namespace OpenBoleto;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:16:49.
 */
class BoletoFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BoletoFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BoletoFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers OpenBoleto\BoletoFactory::loadByBankId
     * @todo   Implement testLoadByBankId().
     */
    public function testLoadByBankId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OpenBoleto\BoletoFactory::loadByBankName
     * @todo   Implement testLoadByBankName().
     */
    public function testLoadByBankName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
